const std = @import("std");

pub const KeyCode = enum(u8) {
    a,
    b,
    c,
    d,
    e,
    f,
    g,
    h,
    i,
    j,
    k,
    l,
    m,
    n,
    o,
    p,
    q,
    r,
    s,
    t,
    u,
    v,
    w,
    x,
    y,
    z,
    digit_0,
    digit_1,
    digit_2,
    digit_3,
    digit_4,
    digit_5,
    digit_6,
    digit_7,
    digit_8,
    digit_9,
    enter,
    escape,
    space,
    tab,
    backspace,
    grave,
    minus,
    equal,
    left_bracket,
    right_bracket,
    backslash,
    semicolon,
    apostrophe,
    comma,
    dot,
    slash,
    left,
    right,
    up,
    down,
    home,
    end,
    page_up,
    page_down,
    insert,
    delete,
    f1,
    f2,
    f3,
    f4,
    f5,
    f6,
    f7,
    f8,
    f9,
    f10,
    f11,
    f12,
    shift_left,
    shift_right,
    ctrl_left,
    ctrl_right,
    alt_left,
    alt_right,
    caps_lock,
    num_lock,
    scroll_lock,
    print_screen,
    pause,
    menu,
};

pub const KeyEvent = struct {
    code: KeyCode,
    pressed: bool,
};

pub fn eventName(event: KeyEvent) []const u8 {
    return @tagName(event.code);
}

const shift_map = [_]u8{ '!', '@', '#', '$', '%', '^', '&', '*', '(', ')' };
const digits = [_]u8{ '0', '1', '2', '3', '4', '5', '6', '7', '8', '9' };

pub fn keyToCodepoint(code: KeyCode, shifted: bool) ?u8 {
    return switch (code) {
        .space => ' ',
        .a => if (shifted) 'A' else 'a',
        .b => if (shifted) 'B' else 'b',
        .c => if (shifted) 'C' else 'c',
        .d => if (shifted) 'D' else 'd',
        .e => if (shifted) 'E' else 'e',
        .f => if (shifted) 'F' else 'f',
        .g => if (shifted) 'G' else 'g',
        .h => if (shifted) 'H' else 'h',
        .i => if (shifted) 'I' else 'i',
        .j => if (shifted) 'J' else 'j',
        .k => if (shifted) 'K' else 'k',
        .l => if (shifted) 'L' else 'l',
        .m => if (shifted) 'M' else 'm',
        .n => if (shifted) 'N' else 'n',
        .o => if (shifted) 'O' else 'o',
        .p => if (shifted) 'P' else 'p',
        .q => if (shifted) 'Q' else 'q',
        .r => if (shifted) 'R' else 'r',
        .s => if (shifted) 'S' else 's',
        .t => if (shifted) 'T' else 't',
        .u => if (shifted) 'U' else 'u',
        .v => if (shifted) 'V' else 'v',
        .w => if (shifted) 'W' else 'w',
        .x => if (shifted) 'X' else 'x',
        .y => if (shifted) 'Y' else 'y',
        .z => if (shifted) 'Z' else 'z',
        .digit_0 => if (shifted) shift_map[9] else digits[0],
        .digit_1 => if (shifted) shift_map[0] else digits[1],
        .digit_2 => if (shifted) shift_map[1] else digits[2],
        .digit_3 => if (shifted) shift_map[2] else digits[3],
        .digit_4 => if (shifted) shift_map[3] else digits[4],
        .digit_5 => if (shifted) shift_map[4] else digits[5],
        .digit_6 => if (shifted) shift_map[5] else digits[6],
        .digit_7 => if (shifted) shift_map[6] else digits[7],
        .digit_8 => if (shifted) shift_map[7] else digits[8],
        .digit_9 => if (shifted) shift_map[8] else digits[9],
        .minus => if (shifted) '_' else '-',
        .equal => if (shifted) '+' else '=',
        .left_bracket => if (shifted) '{' else '[',
        .right_bracket => if (shifted) '}' else ']',
        .backslash => if (shifted) '|' else '\\',
        .semicolon => if (shifted) ':' else ';',
        .apostrophe => if (shifted) '"' else '\'',
        .comma => if (shifted) '<' else ',',
        .dot => if (shifted) '>' else '.',
        .slash => if (shifted) '?' else '/',
        .grave => if (shifted) '~' else '`',
        else => null,
    };
}
