#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

MODE="${1:-generate}"
DOC="boot-log.md"
START_MARKER="ASTER KERNEL ENTRY"
END_MARKER="ASTER FIRST FRAME"
TIMEOUT="${BOOT_LOG_TIMEOUT:-30}"

if [[ "$MODE" != "generate" && "$MODE" != "--check" && "$MODE" != "check" ]]; then
    echo "usage: $0 [--check]"
    echo "  (no args)  capture a fresh boot and regenerate boot-log.md"
    echo "  --check    verify boot-log.md matches a fresh boot (CI)"
    exit 2
fi

zig build iso >/dev/null
ISO="$(find .zig-cache -name aster.iso -printf '%T@ %p\n' | sort -rn | head -1 | cut -d' ' -f2-)"

tmpdir="$(mktemp -d)"
serial_file="$tmpdir/boot.serial"

# A test disk is attached so the captured log demonstrates the storage stack
# (virtio-blk, GPT, ext2) too — the same configuration in both modes keeps
# --check deterministic. BOOT_LOG_DISK overrides the default.
DISK="${BOOT_LOG_DISK:-"$tmpdir/boot-disk.img"}"
if [[ ! -f "$DISK" ]]; then
    ./tools/make-test-disk.sh "$DISK" >/dev/null 2>&1
fi

qemu-system-x86_64 \
    $(./tools/qemu-accel.sh) \
    -M q35 \
    -m 512M \
    -cdrom "$ISO" \
    -drive "file=$DISK,format=raw,if=none,id=hd0" \
    -device virtio-blk-pci,drive=hd0,disable-legacy=on \
    -serial file:"$serial_file" \
    -display none \
    -boot order=d \
    -no-reboot \
    >/dev/null 2>&1 &
qemu_pid=$!

for _ in $(seq 1 "$TIMEOUT"); do
    if grep -q "$END_MARKER" "$serial_file" 2>/dev/null; then
        break
    fi
    sleep 1
done
kill "$qemu_pid" 2>/dev/null || true
wait "$qemu_pid" 2>/dev/null || true

# Extract the OS boot log (kernel serial output from ASTER KERNEL ENTRY to
# ASTER FIRST FRAME — no build/bootloader noise), ANSI colors stripped.
sed -E 's/\x1b\[[0-9;]*m//g' "$serial_file" \
    | tr -d '\r' \
    | awk -v s="$START_MARKER" -v e="$END_MARKER" '
        $0 == s { print; inlog = 1; next }
        inlog && $0 == e { print; exit }
        inlog { print }
      ' > "$tmpdir/plain.log"

if [[ ! -s "$tmpdir/plain.log" ]]; then
    echo "capture-boot: FAIL (boot log not captured; check QEMU / BOOT_LOG_TIMEOUT)"
    rm -rf "$tmpdir"
    exit 1
fi

ACCEL="$(awk '/^\[ OK \] accelerator/{print $NF; exit}' "$tmpdir/plain.log")"
COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
DATE="$(date +%Y-%m-%d)"
HOST="$(hostname 2>/dev/null || echo host)"

# Normalize the accelerator and the measured boot time so KVM/TCG and run-to-
# run jitter do not fail --check: the log body must change only when the
# kernel logging itself changes. The kernel size stays (it is deterministic).
normalize() {
    sed -E 's/\[ OK \] accelerator[[:space:]]+[a-z]+/[ OK ] accelerator ACCEL/; s/(complete · [0-9]+ KiB · )[0-9]+ ms/\1N ms/'
}

if [[ "$MODE" == "--check" || "$MODE" == "check" ]]; then
    if [[ ! -f "$DOC" ]]; then
        echo "capture-boot: FAIL ($DOC missing — run without --check to generate it)"
        rm -rf "$tmpdir"
        exit 1
    fi
    stored="$(sed -n '/^```$/,/^```$/p' "$DOC" | sed '1d;$d' | normalize)"
    fresh="$(normalize < "$tmpdir/plain.log")"
    if [[ "$stored" == "$fresh" ]]; then
        echo "capture-boot: OK (boot-log.md matches a fresh boot)"
        rm -rf "$tmpdir"
        exit 0
    fi
    echo "capture-boot: FAIL (boot-log.md is stale — regenerate with $0)"
    diff -u <(printf '%s\n' "$stored") <(printf '%s\n' "$fresh") || true
    rm -rf "$tmpdir"
    exit 1
fi

cat > "$DOC" <<EOF
# Boot Log

Real terminal output of \`zig build run\` — generated by \`tools/capture-boot.sh\`.

| Field | Value |
|---|---|
| Date | $DATE |
| Host | $HOST |
| Accelerator | $ACCEL |
| Commit | $COMMIT |

\`\`\`
$(cat "$tmpdir/plain.log")
\`\`\`
EOF

rm -rf "$tmpdir"
echo "capture-boot: wrote $DOC"
