#!/usr/bin/env bash
set -e

# Aster OS changelog tooling.
#
# CHANGELOG.md is a HAND-CURATED, aggregated changelog (what the system can
# do, one version per milestone). It is committed and must NOT be overwritten
# by this script.
#
# This script only (re)generates the raw commit history, oldest first and
# verbatim, into a SEPARATE file (CHANGELOG-commits.md) or to stdout. The
# aggregated changelog stays the single source of truth for readers; the raw
# history is always one command away.
#
# Usage:
#   tools/generate-changelog.sh            write raw log to CHANGELOG-commits.md
#   tools/generate-changelog.sh --log      print the raw commit log to stdout
#   tools/generate-changelog.sh --help     show this help

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
    sed -n '4,18p' "$0" | sed 's/^# *//'
    exit 0
fi

if [[ "${1:-}" == "--log" ]]; then
    git log --reverse --format="### %s%n%n%b%n"
    exit 0
fi

# Write the raw commit log to CHANGELOG-commits.md (never touches CHANGELOG.md)
cat << 'EOF' > CHANGELOG-commits.md
# Commit history

Raw, verbatim commit log (oldest first), regenerated with
`tools/generate-changelog.sh`. The aggregated changelog lives in
CHANGELOG.md — do not edit this file by hand.

EOF

git log --reverse --format="### %s%n%n%b%n" >> CHANGELOG-commits.md

COUNT=$(git rev-list --count HEAD)
echo "wrote raw commit log to CHANGELOG-commits.md: $COUNT commits"
